dist: trusty
sudo: false
git:
  depth: 3
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  - TERM=dumb

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew check --stacktrace --no-daemon

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - ./*.jar
  skip_cleanup: true
  on:
    tags: true
